# -*- coding: utf-8 -*-
"""FaceDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cs9YKSZILRcfjT246S1SKZ8K30FW0bip
"""

from google.colab import files
uploaded=files.upload()
import zipfile
import os
with zipfile.ZipFile("archive (2).zip",'r') as zip_ref:
    zip_ref.extractall('emotion_data')

train_dir='emotion_data/train'
test_dir='emotion_data/test'

from tensorflow.keras.preprocessing.image import ImageDataGenerator
img_size=48
train_datagen=ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)
test_datagen=ImageDataGenerator(rescale=1./255)
train_data=train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_size,img_size),
    color_mode='grayscale',
    batch_size=64,
    class_mode='categorical'

)
test_data=test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_size,img_size),
    color_mode='grayscale',
    batch_size=64,
    class_mode='categorical'
)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Dropout,Flatten,Dense

model=Sequential([
    Conv2D(32,(3,3),activation='relu',input_shape=(48,48,1)),
    MaxPooling2D(2,2),
    Dropout(0.25),

    Conv2D(64,(3,3),activation='relu'),
    MaxPooling2D(2,2),
    Dropout(0.25),

    Conv2D(128,(3,3),activation='relu'),
    MaxPooling2D(2,2),
    Dropout(0.25),

    Flatten(),
    Dense(128,activation='relu'),
    Dropout(0.5),
    Dense(train_data.num_classes,activation='softmax')


])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
model.summary()

history=model.fit(
    train_data,
    validation_data=test_data,
    epochs=20,
    verbose=1

)

loss,accuracy=model.evaluate(test_data)
print(f"Test Accuracy:{accuracy*100:.2f}%")

import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'],label='Train Accuracy')
plt.plot(history.history['val_accuracy'],label='Train Accuracy')
plt.legend()
plt.title("Model Accuracy")
plt.show()
plt.plot(history.history['loss'],label='Train Loss')
plt.plot(history.history['val_loss'],label='Test Loss')
plt.legend()
plt.title("Model Loss")
plt.show()

model.save("emotion_model.h5")

!pip install opencv-python
!pip install cvzone

import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

model = load_model("emotion_model.h5")

face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

emotion_labels = list(train_data.class_indices.keys())
print("Emotion Classes:", emotion_labels)

emotion_labels = ['Angry','Disgust','Fear','Happy','Sad','Surprise','Neutral']

from google.colab import files
uploaded = files.upload()

img_path = list(uploaded.keys())[0]

img = cv2.imread(img_path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)
faces = face_cascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=3,
    minSize=(30, 30)
)
print(face_cascade.empty())
if len(faces) == 0:
    print("No face detected")
else:
    for (x, y, w, h) in faces:
        face = gray[y:y+h, x:x+w]
        face = cv2.resize(face, (48, 48))
        face = face / 255.0
        face = np.reshape(face, (1, 48, 48, 1))

        prediction = model.predict(face)
        predicted_index = np.argmax(prediction)
        emotion = emotion_labels[predicted_index]

        # ✅ PRINT EMOTION CLEARLY
        print("Predicted Emotion:", emotion)

        # ✅ Print confidence
        confidence = prediction[0][predicted_index] * 100
        print("Confidence: {:.2f}%".format(confidence))

        # Draw on image
        cv2.rectangle(img, (x, y), (x+w, y+h), (0,255,0), 2)
        cv2.putText(img, emotion, (x, y-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 1,
                    (0,255,0), 2)

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.show()
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Original Image")
plt.axis("off")
plt.show()

from google.colab.patches import cv2_imshow
from IPython.display import Javascript
from google.colab.output import eval_js
from base64 import b64decode
import numpy as np
import cv2

def take_photo(filename='photo.jpg', quality=0.8):
    js = Javascript('''
        async function takePhoto(quality) {
          const div = document.createElement('div');
          const capture = document.createElement('button');
          capture.textContent = 'Capture';
          div.appendChild(capture);

          const video = document.createElement('video');
          video.style.display = 'block';
          const stream = await navigator.mediaDevices.getUserMedia({video: true});
          document.body.appendChild(div);
          div.appendChild(video);
          video.srcObject = stream;
          await video.play();

          google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

          await new Promise((resolve) => capture.onclick = resolve);

          const canvas = document.createElement('canvas');
          canvas.width = video.videoWidth;
          canvas.height = video.videoHeight;
          canvas.getContext('2d').drawImage(video, 0, 0);
          stream.getVideoTracks()[0].stop();
          div.remove();
          return canvas.toDataURL('image/jpeg', quality);
        }
    ''')
    display(js)
    data = eval_js('takePhoto({})'.format(quality))
    binary = b64decode(data.split(',')[1])
    with open(filename, 'wb') as f:
        f.write(binary)
    return filename

filename = take_photo()

img = cv2.imread(filename)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray, 1.3, 5)

for (x, y, w, h) in faces:
    face = gray[y:y+h, x:x+w]
    face = cv2.resize(face, (48, 48))
    face = face / 255.0
    face = np.reshape(face, (1, 48, 48, 1))

    prediction = model.predict(face)
    emotion = emotion_labels[np.argmax(prediction)]

    cv2.rectangle(img, (x, y), (x+w, y+h), (0,255,0), 2)
    cv2.putText(img, emotion, (x, y-10),
                cv2.FONT_HERSHEY_SIMPLEX, 1,
                (0,255,0), 2)

cv2_imshow(img)